### ISSUE TITLE
generate images from train and test

### ISSUE THREAD

**Issue by aliechoes** [marrlab/DomainLab#11]
is it possible to generate the images from the train and test and save them for sanity check?

**Comment by Car-la-F** [comment]
Can you explain a little bit more in detail what the task would be?

I suppose the test shall cover all domains, but do we also test all labels over all domains. How many examples shall be tested. Should you be able to modify how many examples to test?

**Comment by smilesun** [comment]
@Car-la-F 
If you load data on your disk via [TaskFolder(clickme)](https://marrlab.github.io/DomainLab/build/html/doc_tasks.html) or TaskPathList, you wanna make sure the pytorch data loader associated with each domain correspond to the domains on your disk.
Also, you wanna make a  small sample of the large amounts of data on disk to a small proportion so that you can test your algorithm on the laptop.  

The output of this functionality should be a folder with 
- user specifying the path, 
- then how many samples do you need for each domain
- (ideally) you should have each label being sampled with a lower threshold
- each domain comes into subfolder
- via file name you know the class label. 
Clear now? 



Reference code for you to use
- https://github.com/marrlab/DomainLab/blob/80cd6fe4090bd7a18d3efeeb623b3158f1c8c5c1/domainlab/dsets/utils_data.py#L47
- https://github.com/marrlab/DomainLab/blob/80cd6fe4090bd7a18d3efeeb623b3158f1c8c5c1/domainlab/dsets/utils_data.py#L34
- https://github.com/marrlab/DomainLab/blob/master/domainlab/utils/utils_img_sav.py

**Comment by smilesun** [comment]
@Car-la-F , 

please also take a look at this example https://marrlab.github.io/DomainLab/build/html/doc_examples.html#generation-of-images
where generation of image is implemented for DIVA. 

Does this help you to get a feeling?

**Comment by Car-la-F** [comment]
@smilesun 

I'm not sure if I finally got everything right. 
I wrote a prototype inside a test function (as this seemed to be a very easy approach to explore how to solve the issue on the example dataset vlcs_mini) and pushed my code to my branch (carla_GenImages), you can find the code in "tests/test_taskfolder_dset_extraction.py". When running the code it will create a folder "Dset_Extraction" in "zout" containing the plots.
Can you please check if this is how you want it to be?

**Comment by smilesun** [comment]
Good job, please find my comments in the pull request and reply there: https://github.com/marrlab/DomainLab/pull/59

**Comment by smilesun** [comment]
Fixed in [cf8ae10](https://github.com/marrlab/DomainLab/commit/cf8ae10a3092a54277a5d05d203331e149f8ebdc)
