### ISSUE TITLE
taking away the extensions

### ISSUE THREAD

**Issue by aliechoes** [marrlab/DomainLab#16]
in the `mk_task_folder` one needs to specify the `extensions`. However, it would be more straightforward to stick to a standard set of image extensions. It can easily happen that one domain contains various extensions.

**Comment by prockenschaub** [comment]
One could allow for both, a default behaviour when `extensions=None` that looks for a range of commen extensions (.jpg, .png, etc.) and the option to manually specify them.

I am still a bit unclear on how image-specific you want DomainLab to be but a broader point could be to make task defintions mode agnostic.  For example, I talked to @smilesun about my applications, which would be seq2seq time series data. For those cases, just a standard set of image extensions won't work. It's also a bit awkward to specify parameters such as `dict_domain_img_trans` when there are now images. To make it more general, it could for example be changed to `dict_domain_trans` and transformation functions just need to follow a given interface compatible with torchvision transforms.

**Comment by schoersch** [comment]
@aliechoes @smilesun It seems to me, that the extension is ignored by `DsetSubFolder`, also confirmed in `dset_subfolder_test` and `test_task_folder` on branch `default-extensions`. All images are loaded, independent from their codec.

Thus filtering by extensions in `DsetSubFolder` would change the current behavior, although the current one is not what I had expected.

So my proposal would be to allow `extension=None`, which then loads all images with some default extensions (see below). Otherwise, if `extensions` is given as dictionary, only file extensions (str or tuple[str]) listed in the respective entry are loaded.

_Default extensions list:_
Regarding torchvision, there seems to be support at least for [jpeg and png](https://pytorch.org/vision/stable/io.html#image). So as a starting point, the default list could contain:
- jpg
- jpeg
- png

or we go for the full range supported by PIL, see output of `python -m PIL`.

I think the parameter naming issue of @prockenschaub can be separated from this.

**Comment by schoersch** [comment]
Another thing: from @Car-la-F's experience, networks do not generalize to different codecs. Thus to me it seems reasonable to consider different extensions as different domains.

**Comment by smilesun** [comment]
@schoersch , please see my comments in https://github.com/marrlab/DomainLab/pull/60 where we can discuss further on this issue. 

could you first generate a solution about this that is ready for code review?
