### ISSUE TITLE
shuffling of the samples in the mk_loader funtiona

### ISSUE THREAD

**Issue by sidulova** [marrlab/DomainLab#697]
Is there any chance we can have shuffle in the mk_loader function as an arg.parser argument? 
For some of the models that we are implementing in DomId, we would like to have non randomized batching.

https://github.com/marrlab/DomainLab/blob/592f084298e3159c3f3f2b3c3fbc732f5bb4e2c2/domainlab/tasks/utils_task.py#L49

Thank you!

**Comment by smilesun** [comment]
@sidulova , at the moment not, but you can implement it like this

https://github.com/marrlab/DomainLab/blob/592f084298e3159c3f3f2b3c3fbc732f5bb4e2c2/domainlab/arg_parser.py#L196

or simply add such an argument in the major args  @agisga,  but in which scenario you do not want to shuffle?  From a distributed optimization point of view, no shuffle does not make sense.  


Alternatively, the test domain, as well as training domain validation daaset, are not shuffled by default.  See
  https://github.com/marrlab/DomainLab/blob/592f084298e3159c3f3f2b3c3fbc732f5bb4e2c2/domainlab/tasks/b_task.py#L51

@sidulova

**Comment by smilesun** [comment]
@sidulova , maybe you can also take a look at the API coding:

https://github.com/marrlab/DomainLab/blob/master/examples/api/jigen_dann_transformer.py

**Comment by agisga** [comment]
> but in which scenario you do not want to shuffle? From a distributed optimization point of view, no shuffle does not make sense.

It's for a specific use case in digital pathology, where the h and w dimensions of whole slide images (WSI) are about 100,000 pixels, so the WSI is typically cut up into many small image patches, and we don't want to shuffle patches from different WSIs together in our case. Essentially, we are applying a graph neural network based method, where we need each batch to include only patches from the same WSI due to the type of graph construction used.

**Comment by sidulova** [comment]
@smilesun, we have implemented the necessary changes to address the following issue.
Would you mind looking at the pull request? 
https://github.com/marrlab/DomainLab/pull/792
Thank you~!
