### ISSUE TITLE
do we need a property for trainer called decoratee (without ""_"") when self.model is always equal to decoratee? 

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#825]
https://github.com/marrlab/DomainLab/blob/79a2524560f8a654ff4032dc992d35f4b7183027/domainlab/algos/trainers/a_trainer.py#L115

**Comment by smilesun** [comment]
as in the comment of abstract trainer stated, self.decorates can be both model or trainer but self._decoratee can only be trainer, self.get_model() can only be model

**Comment by smilesun** [comment]
after the change below, now self.model can be both trainer and model 

<!DOCTYPE html>
Name |  
-- | --
Latest commitsmilesun2 minutes agoHistoryMerge pull request #823 from marrlab/trainer_as_model4970eb6treat trainer as model

Name	
Latest commit
[smilesun](https://github.com/marrlab/DomainLab/commits?author=smilesun)
smilesun
2 minutes ago
History


[Merge pull request](https://github.com/marrlab/DomainLab/commit/4970eb68f899216ddfc440cdeb97e7a362cb8e34) https://github.com/marrlab/DomainLab/pull/823 [from marrlab/trainer_as_model](https://github.com/marrlab/DomainLab/commit/4970eb68f899216ddfc440cdeb97e7a362cb8e34)

[4970eb6](https://github.com/marrlab/DomainLab/commit/4970eb68f899216ddfc440cdeb97e7a362cb8e34)

treat trainer as model

**Comment by MatteoWohlrapp** [comment]
I don't think so. decoratee acts as an abstraction to check if _decoratee is none, and if so accesses the model instead: 

[    @property
    def decoratee(self):
        if self._decoratee is None:
            return self.model
        return self._decoratee](https://github.com/marrlab/DomainLab/blob/44271c83317128b7a9910fd1d6c51ed751d98b91/domainlab/algos/trainers/a_trainer.py#L114C1-L118C31)
        
 However, we are already assigning _decoratee to model in the constructor and could therefore also directly call self.model instead: 
 
 
[        if self._decoratee is not None:
            self._decoratee.init_business(
                model, task, observer, device, aconf, flag_accept
            )
            self.model = self._decoratee
        else:
            self.model = model](https://github.com/marrlab/DomainLab/blob/44271c83317128b7a9910fd1d6c51ed751d98b91/domainlab/algos/trainers/a_trainer.py#L126C1-L132C31)
 
 
I don't think this is particularly intuitive because model can then also be a trainer. We could leave the decoratee but rename _decoratee to trainer. That way decoratee could make the distinction between model and trainer and we only access decoratee.
